package ports

const (
	DEFAULTHOST     = "localhost"
	DEFAULTPORT_API = "8080"
	DEFAULTHOST_API = DEFAULTHOST
	DEFAULTPORT_DB  = "27017"
	DEFAULTHOST_DB  = DEFAULTHOST
	DEFAULTPORT_APP = "3000"
	DEFAULTHOST_APP = DEFAULTHOST
)
